CREATE TABLE "gyms" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "address" text,
  "phone" varchar(20),
  "deleted_at" timestamp,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "gym_id" int NOT NULL,
  "name" varchar(255) NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "role" "enum(OWNER,STAFF)" NOT NULL DEFAULT 'STAFF',
  "email_verified_at" timestamp,
  "remember_token" varchar(100),
  "deleted_at" timestamp,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "members" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "gym_id" int NOT NULL,
  "member_id" varchar(50) UNIQUE NOT NULL,
  "full_name" varchar(255) NOT NULL,
  "phone" varchar(20) UNIQUE NOT NULL,
  "email" varchar(255) UNIQUE,
  "gender" "enum(M,F,OTHER)",
  "date_of_birth" date,
  "status" "enum(ACTIVE,INACTIVE)" NOT NULL DEFAULT 'ACTIVE',
  "deleted_at" timestamp,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "membership_plans" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "gym_id" int NOT NULL,
  "name" varchar(255) NOT NULL,
  "duration_days" int NOT NULL,
  "price" decimal(10,2) NOT NULL,
  "description" text,
  "is_active" boolean NOT NULL DEFAULT true,
  "deleted_at" timestamp,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "memberships" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" int NOT NULL,
  "membership_plan_id" int NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "status" "enum(ACTIVE,EXPIRED,FROZEN)" NOT NULL DEFAULT 'ACTIVE',
  "auto_renew" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "checkins" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" int NOT NULL,
  "gym_id" int NOT NULL,
  "checked_in_at" timestamp NOT NULL,
  "checked_in_by" varchar(255),
  "deleted_at" timestamp,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "payments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "gym_id" int NOT NULL,
  "member_id" int NOT NULL,
  "amount" decimal(10,2) NOT NULL,
  "payment_for" varchar(50) NOT NULL,
  "method" "enum(CASH,TRANSFER,CARD,E_WALLET)" NOT NULL DEFAULT 'CASH',
  "status" "enum(PAID,PENDING,REFUNDED,CANCELLED)" NOT NULL DEFAULT 'PAID',
  "notes" text,
  "deleted_at" timestamp,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE UNIQUE INDEX ON "users" ("email");

CREATE INDEX ON "users" ("gym_id");

CREATE INDEX ON "users" ("deleted_at");

CREATE UNIQUE INDEX ON "members" ("member_id");

CREATE UNIQUE INDEX ON "members" ("phone");

CREATE UNIQUE INDEX ON "members" ("email");

CREATE INDEX ON "members" ("gym_id");

CREATE INDEX ON "members" ("status");

CREATE INDEX ON "members" ("deleted_at");

CREATE INDEX ON "membership_plans" ("gym_id");

CREATE INDEX ON "membership_plans" ("is_active");

CREATE INDEX ON "membership_plans" ("deleted_at");

CREATE INDEX ON "memberships" ("member_id");

CREATE INDEX ON "memberships" ("membership_plan_id");

CREATE INDEX ON "memberships" ("status", "end_date");

CREATE INDEX ON "memberships" ("deleted_at");

CREATE INDEX ON "checkins" ("member_id");

CREATE INDEX ON "checkins" ("gym_id");

CREATE INDEX ON "checkins" ("checked_in_at");

CREATE INDEX ON "checkins" ("deleted_at");

CREATE INDEX ON "payments" ("gym_id");

CREATE INDEX ON "payments" ("member_id");

CREATE INDEX ON "payments" ("status");

CREATE INDEX ON "payments" ("created_at");

CREATE INDEX ON "payments" ("deleted_at");

COMMENT ON TABLE "gyms" IS 'Gym/Branch master data. Soft delete enabled for safety.';

COMMENT ON COLUMN "gyms"."id" IS 'Primary Key';

COMMENT ON COLUMN "gyms"."name" IS 'Gym name';

COMMENT ON COLUMN "gyms"."address" IS 'Full address';

COMMENT ON COLUMN "gyms"."phone" IS 'Contact phone';

COMMENT ON COLUMN "gyms"."deleted_at" IS 'Soft delete timestamp';

COMMENT ON TABLE "users" IS 'Authentication table. Soft delete for audit trail.';

COMMENT ON COLUMN "users"."id" IS 'Primary Key';

COMMENT ON COLUMN "users"."gym_id" IS 'FK to gyms';

COMMENT ON COLUMN "users"."name" IS 'User full name';

COMMENT ON COLUMN "users"."email" IS 'Login email';

COMMENT ON COLUMN "users"."password" IS 'Hashed password';

COMMENT ON COLUMN "users"."role" IS 'User role';

COMMENT ON COLUMN "users"."deleted_at" IS 'Soft delete timestamp';

COMMENT ON TABLE "members" IS 'CRITICAL: Soft delete only. Preserve for reporting & audit.';

COMMENT ON COLUMN "members"."id" IS 'Primary Key';

COMMENT ON COLUMN "members"."gym_id" IS 'FK to gyms';

COMMENT ON COLUMN "members"."member_id" IS 'Unique code: GYM001';

COMMENT ON COLUMN "members"."full_name" IS 'Member full name';

COMMENT ON COLUMN "members"."phone" IS 'Member phone';

COMMENT ON COLUMN "members"."email" IS 'Member email (optional)';

COMMENT ON COLUMN "members"."gender" IS 'Member gender';

COMMENT ON COLUMN "members"."date_of_birth" IS 'Date of birth';

COMMENT ON COLUMN "members"."status" IS 'Member status';

COMMENT ON COLUMN "members"."deleted_at" IS 'Soft delete - preserves history';

COMMENT ON TABLE "membership_plans" IS 'Membership plans. Cannot delete if used by active memberships.';

COMMENT ON COLUMN "membership_plans"."id" IS 'Primary Key';

COMMENT ON COLUMN "membership_plans"."gym_id" IS 'FK to gyms';

COMMENT ON COLUMN "membership_plans"."name" IS 'Plan name: Bulanan, 3 Bulan';

COMMENT ON COLUMN "membership_plans"."duration_days" IS 'Duration: 30, 90, 365 days';

COMMENT ON COLUMN "membership_plans"."price" IS 'Plan price in IDR';

COMMENT ON COLUMN "membership_plans"."description" IS 'Plan description';

COMMENT ON COLUMN "membership_plans"."is_active" IS 'Active status';

COMMENT ON COLUMN "membership_plans"."deleted_at" IS 'Soft delete timestamp';

COMMENT ON TABLE "memberships" IS 'NEVER hard delete. Critical for revenue reporting & history.';

COMMENT ON COLUMN "memberships"."id" IS 'Primary Key';

COMMENT ON COLUMN "memberships"."member_id" IS 'FK to members';

COMMENT ON COLUMN "memberships"."membership_plan_id" IS 'FK to plans';

COMMENT ON COLUMN "memberships"."start_date" IS 'Membership start date';

COMMENT ON COLUMN "memberships"."end_date" IS 'Membership end date';

COMMENT ON COLUMN "memberships"."status" IS 'Membership status';

COMMENT ON COLUMN "memberships"."auto_renew" IS 'Auto renewal flag';

COMMENT ON COLUMN "memberships"."deleted_at" IS 'Soft delete - preserve history';

COMMENT ON TABLE "checkins" IS 'Attendance logs. Soft delete for complete history.';

COMMENT ON COLUMN "checkins"."id" IS 'Primary Key';

COMMENT ON COLUMN "checkins"."member_id" IS 'FK to members';

COMMENT ON COLUMN "checkins"."gym_id" IS 'FK to gyms';

COMMENT ON COLUMN "checkins"."checked_in_at" IS 'Check-in timestamp';

COMMENT ON COLUMN "checkins"."checked_in_by" IS 'Staff name who checked-in';

COMMENT ON COLUMN "checkins"."deleted_at" IS 'Soft delete - preserve attendance history';

COMMENT ON TABLE "payments" IS 'CRITICAL: NEVER hard delete. Required for tax, audit, compliance.';

COMMENT ON COLUMN "payments"."id" IS 'Primary Key';

COMMENT ON COLUMN "payments"."gym_id" IS 'FK to gyms';

COMMENT ON COLUMN "payments"."member_id" IS 'FK to members';

COMMENT ON COLUMN "payments"."amount" IS 'Payment amount';

COMMENT ON COLUMN "payments"."payment_for" IS 'membership, class, retail';

COMMENT ON COLUMN "payments"."method" IS 'Payment method';

COMMENT ON COLUMN "payments"."status" IS 'Payment status';

COMMENT ON COLUMN "payments"."notes" IS 'Payment notes/reference';

COMMENT ON COLUMN "payments"."deleted_at" IS 'Soft delete - CRITICAL for audit';

ALTER TABLE "users" ADD FOREIGN KEY ("gym_id") REFERENCES "gyms" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "members" ADD FOREIGN KEY ("gym_id") REFERENCES "gyms" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "membership_plans" ADD FOREIGN KEY ("gym_id") REFERENCES "gyms" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "checkins" ADD FOREIGN KEY ("gym_id") REFERENCES "gyms" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "payments" ADD FOREIGN KEY ("gym_id") REFERENCES "gyms" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "memberships" ADD FOREIGN KEY ("member_id") REFERENCES "members" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "checkins" ADD FOREIGN KEY ("member_id") REFERENCES "members" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "payments" ADD FOREIGN KEY ("member_id") REFERENCES "members" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "memberships" ADD FOREIGN KEY ("membership_plan_id") REFERENCES "membership_plans" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
